// flag register is not in this list, because we can't modify it directly

export const registers = ['ip', 'ax', 'bx', 'cx', 'dx', 'si', 'di', 'bp', 'sp']

// source - first column of this csv file: https://raw.githubusercontent.com/GregoryComer/x86-csv/master/x86.csv
// csv file was generated from Intel® 64 and IA-32 architectures software developer's manual volume 2 by Gregory Comer
export const allIntelOpcodes = ['aaa', 'aad', 'aam', 'aas', 'adc', 'adcx', 'add', 'addpd', 'addps', 'addsd', 'addss', 'addsubpd', 'addsubps', 'adox', 'aesdec', 'aesdeclast', 'aesenc', 'aesenclast', 'aesimc', 'aeskeygenassist', 'and', 'andn', 'andnpd', 'andnps', 'andpd', 'andps', 'arpl', 'bextr', 'blendpd', 'blendps', 'blendvpd', 'blendvps', 'blsi', 'blsmsk', 'blsr', 'bndcl', 'bndcn', 'bndcu', 'bndldx', 'bndmk', 'bndmov', 'bndstx', 'bound', 'bsf', 'bsr', 'bswap', 'bt', 'btc', 'btr', 'bts', 'bzhi', 'call', 'cbw', 'cdq', 'cdqe', 'clac', 'clc', 'cld', 'clflush', 'clflushopt', 'cli', 'clts', 'clwb', 'cmc', 'cmova', 'cmovae', 'cmovb', 'cmovbe', 'cmovc', 'cmove', 'cmovg', 'cmovge', 'cmovl', 'cmovle', 'cmovna', 'cmovnae', 'cmovnb', 'cmovnbe', 'cmovnc', 'cmovne', 'cmovng', 'cmovnge', 'cmovnl', 'cmovnle', 'cmovno', 'cmovnp', 'cmovns', 'cmovnz', 'cmovo', 'cmovp', 'cmovpe', 'cmp', 'cmppd', 'cmpps', 'cmps', 'cmpsb', 'cmpsd', 'cmpsq', 'cmpss', 'cmpsw', 'cmpxchg', 'cmpxchg8b', 'cmpxchg16b', 'comisd', 'comiss', 'cpuid', 'cqo', 'crc32', 'cvtdq2pd', 'cvtdq2ps', 'cvtpd2dq', 'cvtpd2pi', 'cvtpd2ps', 'cvtpi2pd', 'cvtpi2ps', 'cvtps2dq', 'cvtps2pd', 'cvtps2pi', 'cvtsd2si', 'cvtsd2ss', 'cvtsi2sd', 'cvtsi2ss', 'cvtss2sd', 'cvtss2si', 'cvttpd2dq', 'cvttpd2pi', 'cvttps2dq', 'cvttps2pi', 'cvttsd2si', 'cvttss2si', 'cwd', 'cwde', 'daa', 'das', 'dec', 'div', 'divpd', 'divps', 'divsd', 'divss', 'dppd', 'dpps', 'emms', 'enter', 'extractps', 'f2xm1', 'fabs', 'fadd', 'faddp', 'fbld', 'fbstp', 'fchs', 'fclex', 'fcmovb', 'fcmovbe', 'fcmove', 'fcmovnb', 'fcmovnbe', 'fcmovne', 'fcmovnu', 'fcmovu', 'fcom', 'fcomi', 'fcomip', 'fcomp', 'fcompp', 'fcos', 'fdecstp', 'fdiv', 'fdivp', 'fdivr', 'fdivrp', 'ffree', 'fiadd', 'ficom', 'ficomp', 'fidiv', 'fidivr', 'fild', 'fimul', 'fincstp', 'finit', 'fist', 'fistp', 'fisttp', 'fisub', 'fisubr', 'fld', 'fld1', 'fldcw', 'fldenv', 'fldl2e', 'fldl2t', 'fldlg2', 'fldln2', 'fldpi', 'fldz', 'fmul', 'fmulp', 'fnclex', 'fninit', 'fnop', 'fnsave', 'fnstcw', 'fnstenv', 'fnstsw', 'fpatan', 'fprem', 'fprem1', 'fptan', 'frndint', 'frstor', 'fsave', 'fscale', 'fsin', 'fsincos', 'fsqrt', 'fst', 'fstcw', 'fstenv', 'fstp', 'fstsw', 'fsub', 'fsubp', 'fsubr', 'fsubrp', 'ftst', 'fucom', 'fucomi', 'fucomip', 'fucomp', 'fucompp', 'fwait', 'fxam', 'fxch', 'fxrstor', 'fxrstor64', 'fxsave', 'fxsave64', 'fxtract', 'fyl2x', 'fyl2xp1', 'haddpd', 'haddps', 'hlt', 'hsubpd', 'hsubps', 'idiv', 'imul', 'in', 'inc', 'ins', 'insb', 'insd', 'insertps', 'insw', 'int', 'into', 'invd', 'invlpg', 'invpcid', 'iret', 'iretd', 'iretq', 'ja', 'jae', 'jb', 'jbe', 'jc', 'jcxz', 'je', 'jecxz', 'jg', 'jge', 'jl', 'jle', 'jmp', 'jna', 'jnae', 'jnb', 'jnbe', 'jnc', 'jne', 'jng', 'jnge', 'jnl', 'jnle', 'jno', 'jnp', 'jns', 'jnz', 'jo', 'jp', 'jpe', 'jpo', 'jrcxz', 'js', 'jz', 'kaddb', 'kaddd', 'kaddq', 'kaddw', 'kandb', 'kandd', 'kandnb', 'kandnd', 'kandnq', 'kandnw', 'kandq', 'kandw', 'kmovb', 'kmovd', 'kmovq', 'kmovw', 'knotb', 'knotd', 'knotq', 'knotw', 'korb', 'kord', 'korq', 'kortestb', 'kortestd', 'kortestq', 'kortestw', 'korw', 'kshiftlb', 'kshiftld', 'kshiftlq', 'kshiftlw', 'kshiftrb', 'kshiftrd', 'kshiftrq', 'kshiftrw', 'ktestb', 'ktestd', 'ktestq', 'ktestw', 'kunpckbw', 'kunpckdq', 'kunpckwd', 'kxnorb', 'kxnord', 'kxnorq', 'kxnorw', 'kxorb', 'kxord', 'kxorq', 'kxorw', 'lahf', 'lar', 'lddqu', 'ldmxcsr', 'lds', 'lea', 'leave', 'les', 'lfence', 'lfs', 'lgdt', 'lgs', 'lidt', 'lldt', 'lmsw', 'lock', 'lods', 'lodsb', 'lodsd', 'lodsq', 'lodsw', 'loop', 'loope', 'loopne', 'lsl', 'lss', 'ltr', 'lzcnt', 'maskmovdqu', 'maskmovq', 'maxpd', 'maxps', 'maxsd', 'maxss', 'mfence', 'minpd', 'minps', 'minsd', 'minss', 'monitor', 'mov', 'movapd', 'movaps', 'movbe', 'movd', 'movddup', 'movdq2q', 'movdqa', 'movdqu', 'movhlps', 'movhpd', 'movhps', 'movlhps', 'movlpd', 'movlps', 'movmskpd', 'movmskps', 'movntdq', 'movntdqa', 'movnti', 'movntpd', 'movntps', 'movntq', 'movq', 'movq2dq', 'movs', 'movsb', 'movsd', 'movshdup', 'movsldup', 'movsq', 'movss', 'movsw', 'movsx', 'movsxd', 'movupd', 'movups', 'movzx', 'mpsadbw', 'mul', 'mulpd', 'mulps', 'mulsd', 'mulss', 'mulx', 'mwait', 'neg', 'nop', 'not', 'or', 'orpd', 'orps', 'out', 'outs', 'outsb', 'outsd', 'outsw', 'pabsb', 'pabsd', 'pabsw', 'packssdw', 'packsswb', 'packusdw', 'packuswb', 'paddb', 'paddd', 'paddq', 'paddsb', 'paddsw', 'paddusb', 'paddusw', 'paddw', 'palignr', 'pand', 'pandn', 'pause', 'pavgb', 'pavgw', 'pblendvb', 'pblendw', 'pclmulqdq', 'pcmpeqb', 'pcmpeqd', 'pcmpeqq', 'pcmpeqw', 'pcmpestri', 'pcmpestrm', 'pcmpgtb', 'pcmpgtd', 'pcmpgtq', 'pcmpgtw', 'pcmpistri', 'pcmpistrm', 'pdep', 'pext', 'pextrb', 'pextrd', 'pextrq', 'pextrw', 'phaddd', 'phaddsw', 'phaddw', 'phminposuw', 'phsubd', 'phsubsw', 'phsubw', 'pinsrb', 'pinsrd', 'pinsrq', 'pinsrw', 'pmaddubsw', 'pmaddwd', 'pmaxsb', 'pmaxsd', 'pmaxsw', 'pmaxub', 'pmaxud', 'pmaxuw', 'pminsb', 'pminsd', 'pminsw', 'pminub', 'pminud', 'pminuw', 'pmovmskb', 'pmovsxbd', 'pmovsxbq', 'pmovsxbw', 'pmovsxdq', 'pmovsxwd', 'pmovsxwq', 'pmovzxbd', 'pmovzxbq', 'pmovzxbw', 'pmovzxdq', 'pmovzxwd', 'pmovzxwq', 'pmuldq', 'pmulhrsw', 'pmulhuw', 'pmulhw', 'pmulld', 'pmullw', 'pmuludq', 'pop', 'popa', 'popad', 'popcnt', 'popf', 'popfd', 'popfq', 'por', 'prefetchnta', 'prefetcht0', 'prefetcht1', 'prefetcht2', 'prefetchw', 'prefetchwt1', 'psadbw', 'pshufb', 'pshufd', 'pshufhw', 'pshuflw', 'pshufw', 'psignb', 'psignd', 'psignw', 'pslld', 'pslldq', 'psllq', 'psllw', 'psrad', 'psraw', 'psrld', 'psrldq', 'psrlq', 'psrlw', 'psubb', 'psubd', 'psubq', 'psubsb', 'psubsw', 'psubusb', 'psubusw', 'psubw', 'ptest', 'ptwrite', 'punpckhbw', 'punpckhdq', 'punpckhqdq', 'punpckhwd', 'punpcklbw', 'punpckldq', 'punpcklqdq', 'punpcklwd', 'push', 'pusha', 'pushad', 'pushf', 'pushfd', 'pushfq', 'pxor', 'rcl', 'rcpps', 'rcpss', 'rcr', 'rdfsbase', 'rdgsbase', 'rdmsr', 'rdpid', 'rdpkru', 'rdpmc', 'rdrand', 'rdseed', 'rdtsc', 'rdtscp', 'ret', 'rol', 'ror', 'rorx', 'roundpd', 'roundps', 'roundsd', 'roundss', 'rsm', 'rsqrtps', 'rsqrtss', 'sahf', 'sal', 'sar', 'sarx', 'sbb', 'scas', 'scasb', 'scasd', 'scasq', 'scasw', 'seta', 'setae', 'setb', 'setbe', 'setc', 'sete', 'setg', 'setge', 'setl', 'setle', 'setna', 'setnae', 'setnb', 'setnbe', 'setnc', 'setne', 'setng', 'setnge', 'setnl', 'setnle', 'sfence', 'sgdt', 'sha1msg1', 'sha1msg2', 'sha1nexte', 'sha1rnds4', 'sha256msg1', 'sha256msg2', 'sha256rnds2', 'shl', 'shld', 'shlx', 'shr', 'shrd', 'shrx', 'shufpd', 'shufps', 'sidt', 'sldt', 'smsw', 'sqrtpd', 'sqrtps', 'sqrtsd', 'sqrtss', 'stac', 'stc', 'std', 'sti', 'stmxcsr', 'stos', 'stosb', 'stosd', 'stosq', 'stosw', 'str', 'sub', 'subpd', 'subps', 'subsd', 'subss', 'swapgs', 'syscall', 'sysenter', 'sysexit', 'sysret', 'test', 'tzcnt', 'ucomisd', 'ucomiss', 'ud0', 'ud1', 'ud2', 'unpckhpd', 'unpckhps', 'unpcklpd', 'unpcklps', 'vaddpd', 'vaddps', 'vaddsd', 'vaddss', 'vaddsubpd', 'vaddsubps', 'vaesdec', 'vaesdeclast', 'vaesenc', 'vaesenclast', 'vaesimc', 'vaeskeygenassist', 'valignd', 'valignq', 'vandnpd', 'vandnps', 'vandpd', 'vandps', 'vblendmpd', 'vblendmps', 'vblendpd', 'vblendps', 'vblendvpd', 'vblendvps', 'vbroadcastf32x2', 'vbroadcastf32x4', 'vbroadcastf64x2', 'vbroadcastf128', 'vbroadcasti32x2', 'vbroadcasti32x4', 'vbroadcasti32x8', 'vbroadcasti64x2', 'vbroadcasti64x4', 'vbroadcasti128', 'vbroadcastsd', 'vbroadcastss', 'vcmppd', 'vcmpps', 'vcmpsd', 'vcmpss', 'vcomisd', 'vcomiss', 'vcompresspd', 'vcompressps', 'vcvtdq2pd', 'vcvtdq2ps', 'vcvtpd2dq', 'vcvtpd2ps', 'vcvtpd2qq', 'vcvtpd2udq', 'vcvtpd2uqq', 'vcvtph2ps', 'vcvtps2dq', 'vcvtps2pd', 'vcvtps2ph', 'vcvtps2qq', 'vcvtps2udq', 'vcvtps2uqq', 'vcvtqq2pd', 'vcvtqq2ps', 'vcvtsd2si', 'vcvtsd2ss', 'vcvtsd2usi', 'vcvtsi2sd', 'vcvtsi2ss', 'vcvtss2sd', 'vcvtss2si', 'vcvtss2usi', 'vcvttpd2dq', 'vcvttpd2qq', 'vcvttpd2udq', 'vcvttpd2uqq', 'vcvttps2dq', 'vcvttps2qq', 'vcvttps2udq', 'vcvttps2uqq', 'vcvttsd2si', 'vcvttsd2usi', 'vcvttss2si', 'vcvttss2usi', 'vcvtudq2pd', 'vcvtudq2ps', 'vcvtuqq2pd', 'vcvtuqq2ps', 'vcvtusi2sd', 'vcvtusi2ss', 'vdbpsadbw', 'vdivpd', 'vdivps', 'vdivsd', 'vdivss', 'vdppd', 'vdpps', 'verr', 'verw', 'vexp2pd', 'vexp2ps', 'vexpandpd', 'vexpandps', 'vextractf32x4', 'vextractf64x4', 'vextractf128', 'vextracti32x4', 'vextracti64x4', 'vextracti128', 'vextractps', 'vfixupimmpd', 'vfixupimmps', 'vfixupimmsd', 'vfixupimmss', 'vfmadd132pd', 'vfmadd132ps', 'vfmadd132sd', 'vfmadd132ss', 'vfmadd213pd', 'vfmadd213ps', 'vfmadd213sd', 'vfmadd213ss', 'vfmadd231pd', 'vfmadd231ps', 'vfmadd231sd', 'vfmadd231ss', 'vfmaddsub132pd', 'vfmaddsub132ps', 'vfmaddsub213pd', 'vfmaddsub213ps', 'vfmaddsub231pd', 'vfmaddsub231ps', 'vfmsub132pd', 'vfmsub132ps', 'vfmsub132sd', 'vfmsub132ss', 'vfmsub213pd', 'vfmsub213ps', 'vfmsub213sd', 'vfmsub213ss', 'vfmsub231pd', 'vfmsub231ps', 'vfmsub231sd', 'vfmsub231ss', 'vfmsubadd132pd', 'vfmsubadd132ps', 'vfmsubadd213pd', 'vfmsubadd213ps', 'vfmsubadd231pd', 'vfmsubadd231ps', 'vfnmadd132pd', 'vfnmadd132ps', 'vfnmadd132sd', 'vfnmadd132ss', 'vfnmadd213pd', 'vfnmadd213ps', 'vfnmadd213sd', 'vfnmadd213ss', 'vfnmadd231pd', 'vfnmadd231ps', 'vfnmadd231sd', 'vfnmadd231ss', 'vfnmsub132pd', 'vfnmsub132ps', 'vfnmsub132sd', 'vfnmsub132ss', 'vfnmsub213pd', 'vfnmsub213ps', 'vfnmsub213sd', 'vfnmsub213ss', 'vfnmsub231pd', 'vfnmsub231ps', 'vfnmsub231sd', 'vfnmsub231ss', 'vfpclasspd', 'vfpclassps', 'vfpclasssd', 'vfpclassss', 'vgatherdpd', 'vgatherdps', 'vgatherpf0dpd', 'vgatherpf0dps', 'vgatherpf0qpd', 'vgatherpf0qps', 'vgatherpf1dpd', 'vgatherpf1dps', 'vgatherpf1qpd', 'vgatherpf1qps', 'vgatherqpd', 'vgatherqps', 'vgetexppd', 'vgetexpps', 'vgetexpsd', 'vgetexpss', 'vgetmantpd', 'vgetmantps', 'vgetmantsd', 'vgetmantss', 'vhaddpd', 'vhaddps', 'vhsubpd', 'vhsubps', 'vinsertf128', 'vinserti128', 'vinsertps', 'vlddqu', 'vldmxcsr', 'vmaskmovdqu', 'vmaskmovpd', 'vmaskmovps', 'vmaxpd', 'vmaxps', 'vmaxsd', 'vmaxss', 'vminpd', 'vminps', 'vminsd', 'vminss', 'vmovapd', 'vmovaps', 'vmovd', 'vmovddup', 'vmovdqa', 'vmovdqa32', 'vmovdqa64', 'vmovdqu', 'vmovdqu8', 'vmovdqu16', 'vmovdqu32', 'vmovdqu64', 'vmovhlps', 'vmovhpd', 'vmovhps', 'vmovlhps', 'vmovlpd', 'vmovlps', 'vmovmskpd', 'vmovmskps', 'vmovntdq', 'vmovntdqa', 'vmovntpd', 'vmovntps', 'vmovq', 'vmovsd', 'vmovshdup', 'vmovsldup', 'vmovss', 'vmovupd', 'vmovups', 'vmpsadbw', 'vmulpd', 'vmulps', 'vmulsd', 'vmulss', 'vorpd', 'vorps', 'vpabsb', 'vpabsd', 'vpabsw', 'vpackssdw', 'vpacksswb', 'vpackusdw', 'vpackuswb', 'vpaddb', 'vpaddd', 'vpaddq', 'vpaddsb', 'vpaddsw', 'vpaddusb', 'vpaddusw', 'vpaddw', 'vpalignr', 'vpand', 'vpandd', 'vpandn', 'vpandnd', 'vpandnq', 'vpandq', 'vpavgb', 'vpavgw', 'vpblendd', 'vpblendmb', 'vpblendmd', 'vpblendmq', 'vpblendmw', 'vpblendvb', 'vpblendw', 'vpbroadcastb', 'vpbroadcastd', 'vpbroadcastmb2q', 'vpbroadcastmw2d', 'vpbroadcastq', 'vpbroadcastw', 'vpclmulqdq', 'vpcmpb', 'vpcmpd', 'vpcmpeqb', 'vpcmpeqd', 'vpcmpeqq', 'vpcmpeqw', 'vpcmpestri', 'vpcmpestrm', 'vpcmpgtb', 'vpcmpgtd', 'vpcmpgtq', 'vpcmpgtw', 'vpcmpistri', 'vpcmpistrm', 'vpcmpq', 'vpcmpub', 'vpcmpud', 'vpcmpuq', 'vpcmpuw', 'vpcmpw', 'vpcompressd', 'vpcompressq', 'vpconflictd', 'vpconflictq', 'vperm2f128', 'vperm2i128', 'vpermd', 'vpermi2d', 'vpermi2pd', 'vpermi2ps', 'vpermi2q', 'vpermi2w', 'vpermilpd', 'vpermilps', 'vpermpd', 'vpermps', 'vpermq', 'vpermt2d', 'vpermt2pd', 'vpermt2ps', 'vpermt2q', 'vpermt2w', 'vpermw', 'vpexpandd', 'vpexpandq', 'vpextrb', 'vpextrd', 'vpextrq', 'vpextrw', 'vpgatherdd', 'vpgatherdq', 'vpgatherqd', 'vpgatherqq', 'vphaddd', 'vphaddsw', 'vphaddw', 'vphminposuw', 'vphsubd', 'vphsubsw', 'vphsubw', 'vpinsrb', 'vpinsrd', 'vpinsrq', 'vpinsrw', 'vplzcntd', 'vplzcntq', 'vpmaddubsw', 'vpmaddwd', 'vpmaskmovd', 'vpmaskmovq', 'vpmaxsb', 'vpmaxsd', 'vpmaxsw', 'vpmaxub', 'vpmaxud', 'vpmaxuq', 'vpmaxuw', 'vpminsb', 'vpminsd', 'vpminsq', 'vpminsw', 'vpminub', 'vpminud', 'vpminuq', 'vpminuw', 'vpmovb2m', 'vpmovd2m', 'vpmovdb', 'vpmovdw', 'vpmovm2b', 'vpmovm2d', 'vpmovm2q', 'vpmovm2w', 'vpmovmskb', 'vpmovq2m', 'vpmovqb', 'vpmovqd', 'vpmovqw', 'vpmovsdb', 'vpmovsdw', 'vpmovsqb', 'vpmovsqd', 'vpmovsqw', 'vpmovswb', 'vpmovsxbd', 'vpmovsxbq', 'vpmovsxbw', 'vpmovsxdq', 'vpmovsxwd', 'vpmovsxwq', 'vpmovusdb', 'vpmovusdw', 'vpmovusqb', 'vpmovusqd', 'vpmovusqw', 'vpmovuswb', 'vpmovw2m', 'vpmovwb', 'vpmovzxbd', 'vpmovzxbq', 'vpmovzxbw', 'vpmovzxdq', 'vpmovzxwd', 'vpmovzxwq', 'vpmuldq', 'vpmulhrsw', 'vpmulhuw', 'vpmulhw', 'vpmulld', 'vpmullq', 'vpmullw', 'vpmuludq', 'vpor', 'vpord', 'vporq', 'vprold', 'vprolq', 'vprolvd', 'vprolvq', 'vprord', 'vprorq', 'vprorvd', 'vprorvq', 'vpsadbw', 'vpscatterdd', 'vpscatterdq', 'vpscatterqd', 'vpscatterqq', 'vpshufb', 'vpshufd', 'vpshufhw', 'vpshuflw', 'vpsignb', 'vpsignd', 'vpsignw', 'vpslld', 'vpslldq', 'vpsllq', 'vpsllvd', 'vpsllvq', 'vpsllvw', 'vpsllw', 'vpsrad', 'vpsraq', 'vpsravd', 'vpsravq', 'vpsravw', 'vpsraw', 'vpsrld', 'vpsrldq', 'vpsrlq', 'vpsrlvd', 'vpsrlvq', 'vpsrlvw', 'vpsrlw', 'vpsubb', 'vpsubd', 'vpsubq', 'vpsubsb', 'vpsubsw', 'vpsubusb', 'vpsubusw', 'vpsubw', 'vpternlogd', 'vpternlogq', 'vptest', 'vptestmb', 'vptestmd', 'vptestmq', 'vptestmw', 'vptestnmb', 'vptestnmd', 'vptestnmq', 'vptestnmw', 'vpunpckhbw', 'vpunpckhdq', 'vpunpckhqdq', 'vpunpckhwd', 'vpunpcklbw', 'vpunpckldq', 'vpunpcklqdq', 'vpunpcklwd', 'vpxor', 'vpxord', 'vpxorq', 'vrangepd', 'vrangeps', 'vrangesd', 'vrangess', 'vrcp14pd', 'vrcp14ps', 'vrcp14sd', 'vrcp14ss', 'vrcp28pd', 'vrcp28ps', 'vrcp28sd', 'vrcp28ss', 'vrcpps', 'vrcpss', 'vreducepd', 'vreduceps', 'vreducesd', 'vreducess', 'vrndscalepd', 'vrndscaleps', 'vrndscalesd', 'vrndscaless', 'vroundpd', 'vroundps', 'vroundsd', 'vroundss', 'vrsqrt14pd', 'vrsqrt14ps', 'vrsqrt14sd', 'vrsqrt14ss', 'vrsqrt28pd', 'vrsqrt28ps', 'vrsqrt28sd', 'vrsqrt28ss', 'vrsqrtps', 'vrsqrtss', 'vscalefpd', 'vscalefps', 'vscalefsd', 'vscalefss', 'vscatterdpd', 'vscatterdps', 'vscatterpf0dpd', 'vscatterpf0dps', 'vscatterpf0qpd', 'vscatterpf0qps', 'vscatterpf1dpd', 'vscatterpf1dps', 'vscatterpf1qpd', 'vscatterpf1qps', 'vscatterqpd', 'vscatterqps', 'vshuff32x4', 'vshuff64x2', 'vshufi32x4', 'vshufi64x2', 'vshufpd', 'vshufps', 'vsqrtpd', 'vsqrtps', 'vsqrtsd', 'vsqrtss', 'vstmxcsr', 'vsubpd', 'vsubps', 'vsubsd', 'vsubss', 'vtestpd', 'vtestps', 'vucomisd', 'vucomiss', 'vunpckhpd', 'vunpckhps', 'vunpcklpd', 'vunpcklps', 'vxorpd', 'vxorps', 'vzeroall', 'vzeroupper', 'wait', 'wbinvd', 'wrfsbase', 'wrgsbase', 'wrmsr', 'wrpkru', 'xabort', 'xacquire', 'xadd', 'xbegin', 'xchg', 'xend', 'xgetbv', 'xlat', 'xlatb', 'xor', 'xorpd', 'xorps', 'xrelease', 'xrstor', 'xrstor64', 'xrstors', 'xrstors64', 'xsave', 'xsave64', 'xsavec', 'xsavec64', 'xsaveopt', 'xsaveopt64', 'xsaves', 'xsaves64', 'xsetbv', 'xtest']
export const allIntelRegisters = [
    'ax', 'al', 'ah',
    'bx', 'bl', 'bh',
    'cx', 'cl', 'ch',
    'dx', 'dl', 'dh',
    'cs', 'ds', 'ss', 'es',
    'si', 'di', 'bp', 'sp', 'ip'
]
export const allFlags = ['cf', 'pf', 'af', 'zf', 'sf', 'tf', 'if', 'df', 'of']


export const allIntel16bitRegisters = [
    'ax',
    'bx',
    'cx',
    'dx',
    'cs', 'ds', 'ss', 'es',
    'si', 'di', 'bp', 'sp', 'ip'
]
export const allIntelSegmentRegisters = ['cs', 'ds', 'ss', 'es']

export const allIntel8bitRegisters = [
    'al', 'ah',
    'bl', 'bh',
    'cl', 'ch',
    'dl', 'dh',
]

// source https://gist.github.com/hodgef/e190731ab6c5d297ab22e25811d8fea9
export let keyCodesToKeyNames = {
    8: "backspace",
    9: "tab",
    13: "enter",
    16: "shift",
    17: "ctrl",
    18: "alt",
    19: "pause",
    20: "capslock",
    27: "escape",
    33: "pageup",
    34: "pagedown",
    35: "end",
    36: "home",
    37: "arrowleft",
    38: "arrowup",
    39: "arrowright",
    40: "arrowdown",
    45: "insert",
    46: "delete",
    48: "0",
    49: "1",
    50: "2",
    51: "3",
    52: "4",
    53: "5",
    54: "6",
    55: "7",
    56: "8",
    57: "9",
    65: "a",
    66: "b",
    67: "c",
    68: "d",
    69: "e",
    70: "f",
    71: "g",
    72: "h",
    73: "i",
    74: "j",
    75: "k",
    76: "l",
    77: "m",
    78: "n",
    79: "o",
    80: "p",
    81: "q",
    82: "r",
    83: "s",
    84: "t",
    85: "u",
    86: "v",
    87: "w",
    88: "x",
    89: "y",
    90: "z",
    91: "metaleft",
    92: "metaright",
    93: "select",
    96: "numpad0",
    97: "numpad1",
    98: "numpad2",
    99: "numpad3",
    100: "numpad4",
    101: "numpad5",
    102: "numpad6",
    103: "numpad7",
    104: "numpad8",
    105: "numpad9",
    106: "numpadmultiply",
    107: "numpadadd",
    109: "numpadsubtract",
    110: "numpaddecimal",
    111: "numpaddivide",
    112: "f1",
    113: "f2",
    114: "f3",
    115: "f4",
    116: "f5",
    117: "f6",
    118: "f7",
    119: "f8",
    120: "f9",
    121: "f10",
    122: "f11",
    123: "f12",
    144: "numlock",
    145: "scrolllock",
    186: "semicolon",
    187: "equalsign",
    188: "comma",
    189: "minus",
    190: "period",
    191: "slash",
    192: "backquote",
    219: "bracketleft",
    220: "backslash",
    221: "braketright",
    222: "quote"
};
